### ISSUE TITLE
Incoming track bitrate isn't updated if client stops sending encoding

### ISSUE THREAD

**Issue by asherkin** [medooze/media-server-node#160]
When using simulcast with multiple encodings in Chrome, if the connection becomes bandwidth constrained it will stop sending the higher bitrate encodings.

When this happens the `bitrate` value returned in `IncomingMediaStreamTrack.getStats()` will stop being updated and remain at the last value, which causes it to never drop to 0, which means the encoding is never considered inactive and thus continues to be considered by `Transponder.setTargetBitrate()`.

I had a poke through `media-server` and it _looks_ like the bitrate accumulator is only fed when there is actual media data received, which would explain the behaviour here I think.

**Comment by murillo128** [comment]
Umm... that's weird, the encoding stats should be updated here:

https://github.com/medooze/media-server-node/blob/master/lib/IncomingStreamTrack.js#L203

(note that there is a 200ms period in which `getStats()` will return a cached value instead of recalculating everything again)

I assume that you are refiering to the `stats[encodingId].bitrate` right?

**Comment by murillo128** [comment]
I think that the problem is that the accumulator is updated, but the bitrate stat in `RTPSource` is not recalculated.

**Comment by murillo128** [comment]
should be fixed in ` medooze-media-server@0.95.4`. Could you check it please?

**Comment by asherkin** [comment]
Thanks for the quick fix, that's fixed it right up!
