### ISSUE TITLE
mcu feature

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-node#20]
hi Murillo:
i see the media-server has mcu support,  will media-server-node support that? and where i can find media-server mcu docs?

**Comment by murillo128** [comment]
I still have pending the migration of the java mcu from sourceforge: 
https://sourceforge.net/projects/mcumediaserver

I don't have plans yet to port the mcu functionalities to the media-server-node, mainly due to all the dependencies it requires to be compiled. If I am able to get plugin-like architecture for  integrating the media encoders/decoders, I might incude the mcu functionality as well.
